namespace Fatec.LabEngSoftIII.Zhang.Api.Utils
{
    public static class Extensoes
    {
        public static string RemoverAcentos(this string texto)
        {
            return texto.Replace("Á", "A")
                        .Replace("á", "a")
                        .Replace("Â", "A")
                        .Replace("â", "a")
                        .Replace("À", "A")
                        .Replace("à", "a")
                        .Replace("Å", "A")
                        .Replace("å", "a")
                        .Replace("Ã", "A")
                        .Replace("ã", "a")
                        .Replace("Ä", "A")
                        .Replace("ä", "a")
                        .Replace("ï", "i")
                        .Replace("É", "E")
                        .Replace("é", "e")
                        .Replace("Ê", "E")
                        .Replace("ê", "e")
                        .Replace("È", "E")
                        .Replace("è", "e")
                        .Replace("Ë", "E")
                        .Replace("ë", "e")
                        .Replace("Ð", "D")
                        .Replace("ð", "o")
                        .Replace("õ", "o")
                        .Replace("Í", "I")
                        .Replace("í", "i")
                        .Replace("Î", "I")
                        .Replace("î", "i")
                        .Replace("Ì", "I")
                        .Replace("ì", "i")
                        .Replace("Ï", "I")
                        .Replace("Ù", "U")
                        .Replace("ù", "u")
                        .Replace("Ó", "O")
                        .Replace("ó", "o")
                        .Replace("Ô", "O")
                        .Replace("ô", "o")
                        .Replace("Ò", "O")
                        .Replace("ò", "o")
                        .Replace("Ø", "O")
                        .Replace("Ñ", "N")
                        .Replace("ø", "o")
                        .Replace("ñ", "n")
                        .Replace("Õ", "O")
                        .Replace("Ý", "Y")
                        .Replace("Ö", "O")
                        .Replace("ý", "y")
                        .Replace("ö", "o")
                        .Replace("Ú", "U")
                        .Replace("ú", "u")
                        .Replace("Û", "U")
                        .Replace("û", "u");
        }
    }
}
